version: '3.9'

services:
  web:
    build: .
    command: gunicorn AnimalNest.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app   # 👈 VERY IMPORTANT (keeps db + media persistent)
    ports:
      - "8000:8000"