# Generated by Django 4.2 on 2024-08-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_adoption_adopter_alter_appointment_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.adopter'),
        ),
    ]
