# Generated by Django 4.2 on 2024-08-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_employee_appointment_adopter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='picture',
        ),
        migrations.AddField(
            model_name='pet',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
